### ISSUE TITLE
No ability to destroy the mfa session

### ISSUE THREAD

**Issue by psujohn** [jaredonline/google-authenticator#24]
Unless I missed it there's no way to destroy the mfa session (cookie) on demand. I'd like to be able to destroy it when the user hits logout (as opposed to timing out) which is what github does.

If there really is no way to do this I'd be happy to see if I can add it.

**Comment by jaredonline** [comment]
You're right, there's no way to manually delete the MFA cookie, but it should be super easy to add. Take a look at [how its created](https://github.com/jaredonline/google-authenticator/blob/master/lib/google-authenticator-rails/session/persistence.rb#L28-L32). I'd love to approve a pull request [=
