### ISSUE TITLE
Secure MFA cookie

### ISSUE THREAD

**Issue by Zyphrax** [jaredonline/google-authenticator#26]
Perhaps it would be a good idea to disable javascript access to the MFA cookie (httponly: true) and to secure it when the site is running over SSL (secure: true).

It should be as easy as adding two lines to [persistence.rb](https://github.com/jaredonline/google-authenticator/blob/master/lib/google-authenticator-rails/session/persistence.rb).

Before:
```ruby
def create_cookie(token, user_id)
  value = [token, user_id].join('::')
  {
    :value    => value,
    :expires  => GoogleAuthenticatorRails.time_until_expiration.from_now
  }
end
```
After:
```ruby
def create_cookie(token, user_id)
  value = [token, user_id].join('::')
  {
    :value    => value,
    :expires  => GoogleAuthenticatorRails.time_until_expiration.from_now,
    :secure   => Rails.application.config.force_ssl
    :httponly => true,
  }
end
```

I'm not sure if Rails.application.config.force_ssl is the best default, it would probably be better to make it configurable (just like time_until_expiration).

**Comment by jaredonline** [comment]
Heya @Zyphrax this is great! Is there any chance you can open a pull request for this? I agree that using `Rails.application.config.force_ssl` probably isn't the best option. It probably makes more sense for it to be configurable.

**Comment by Zyphrax** [comment]
Hi @jaredonline, I saw your note on my pull request.

"If you have multiple classes using MFA you'll trounce your cookies here."
True, it would probably be better to move all of this configuration (time_until_expiration, cookie_key and cookie_options) to the model that is decorated with MFA.

I'm afraid that change is a bit out of my depth :), shall I update the pull request to remove the cookie_key configuration?

**Comment by jaredonline** [comment]
Ah! I didn't look here for it.

I think a simple fix would be to have the cookie key just be a suffix for cookie keys:

```ruby
key = "#{GoogleAuthenticatorRails.cookie_key}" || "mfa_credentials"
"#{klass.to_s.downcase}_#{key}"
```

**Comment by Zyphrax** [comment]
I noticed a small bug in handling the default value of cookie_key.
I've created a pull request to fix it.

**Comment by Zyphrax** [comment]
Thanks for pushing the new version!
Case closed :)
