### ISSUE TITLE
:issuer => 'App Name' doesn't work

### ISSUE THREAD

**Issue by Focinfi** [jaredonline/google-authenticator#30]
I added the following code into users.rb, but it doesn't work
`acts_as_google_authenticated issuer: 'My App'`

**Comment by jaredonline** [comment]
Hey @Focinfi, can you give some more details? In what way doesn't it work?

**Comment by Focinfi** [comment]
@jaredonline thanks for your reply, I mean the there is no 'My App' at the top of the item in Google Authenticator App
