### ISSUE TITLE
should we use save! in set_google_secret method?

### ISSUE THREAD

**Issue by goromlagche** [jaredonline/google-authenticator#35]
`set_google_secret` method tries to `save` the record after setting `google_secret` https://github.com/jaredonline/google-authenticator/blob/master/lib/google-authenticator-rails/active_record/helpers.rb#L6

Question I have is should it use `save!`, as `save` does not raise any error.

**Comment by jaredonline** [comment]
Heya @goromlagche sorry its taken me 3.5 months to get back to you. Did you run into an issue where it was unable to set the secret and save? Maybe validations got in the way or something?

**Comment by jaredonline** [comment]
Closed by #41
