### ISSUE TITLE
Any reason for having strict version dependency on ROTP 1.6.1

### ISSUE THREAD

**Issue by danishsatkut** [jaredonline/google-authenticator#42]
Multiple versions of `rotp`library have been released since `1.6.1` which was in Jan, 2014. I am wondering, why this gem has not updated the `rotp` version in its dependency?

**Comment by jaredonline** [comment]
@danishsatkut no reason. I think `1.6.1` was the most recent version when I wrote the gem. If more recent versions work, I'd definitely merge a pull request with a bumped version.

**Comment by 4geru** [comment]
I strongly wish to update version `rotp` 2.0.0. because default padding setting is changed  false into true.

```
require 'rotp'
require 'time'
time = Time.parse('2018-11-31 15:39:46 UTC')
secret = 'JBSWY3DPEHPK3PXP'

totp = ROTP::TOTP.new(secret)
timecode = totp.send(:timecode, time)
puts "1.6.1 #{totp.generate_otp(timecode, false)}" # => 1.6.1 62906
puts "2.0.0 #{totp.generate_otp(timecode)}"        # => 2.0.0 062906
```

https://github.com/mdp/rotp/blame/c82113eee6c9e7d0a03df8cf65ea50a2653c3916/lib/rotp/totp.rb#L29

**Comment by jaredonline** [comment]
Just merged #49 that bumps rotp to 3.3.0 and will release a new version today.

**Comment by 4geru** [comment]
please release it :pray:

**Comment by jaredonline** [comment]
@4geru sorry, forgot to cut the release. Just release 2.0.0 today, you should be good to go.

**Comment by jaredonline** [comment]
Yep! Thanks for pinging again [=
