### ISSUE TITLE
undefined method `prepend_before_filter' for ActionController::Base:Class

### ISSUE THREAD

**Issue by Maxeeezy** [jaredonline/google-authenticator#58]
After bundling the gem, I get the error message above and neither can start my application nor generaate the migrations. I use rails 5 and ruby 2.6.

I could not find anything about this error message online and also was not able to find out how to deal with this issue.

Any ideas what I could do?

**Comment by MeetChavda** [comment]
Having same issue...
you got any solution ?

**Comment by aman-s18** [comment]
I got the same issue.
