### ISSUE TITLE
Newer Version of ROTP 

### ISSUE THREAD

**Issue by HFT-turnet** [jaredonline/google-authenticator#60]
With Ruby 3.0 I get the following error when calling up user.google_qr_uri: .bundle/ruby/3.0.0/gems/rotp-3.3.0/lib/rotp/totp.rb:84:in `provisioning_uri': undefined method `encode' for URI:Module (NoMethodError).

This seems to be resolved with an updated dependency. Unfortunately I do not know how to do that, which is why I did not open a pull request.

**Comment by PeaceS** [comment]
Been facing this issue as well

**Comment by johan-smits** [comment]
If you don't really need a url you can also use the google_qr_to_base64 option. This doesn't use the GoogleQR lib with the error in it.

I have patched out the option and also bumped the rotp library: https://github.com/LeftClickBV/google-authenticator

**Comment by johan-smits** [comment]
If you don't really need a url you can also use the google_qr_to_base64 option. This doesn't use the GoogleQR lib with the error in it.

I have patched out the option and also bumped the rotp library: https://github.com/LeftClickBV/google-authenticator

**Comment by jaredonline** [comment]
@HFT-turnet this should be fixed via #63
