### ISSUE TITLE
`RailsAdapter::LoadedTooLateError` occurs if Zeitwerk is enabled

### ISSUE THREAD

**Issue by kg8m** [jaredonline/google-authenticator#75]
Hi. Thank you for developing this gem.

I have an issue where `GoogleAuthenticatorRails::ActionController::RailsAdapter::LoadedTooLateError` occurs when running RSpec tests on Rails with Zeitwerk. This issue is the same as mentioned in https://github.com/jaredonline/google-authenticator/pull/63#issuecomment-1159866679.

This issue is caused by `defined?(::ApplicationController)` always returning `"constant"` when Zeitwerk is enabled. Zeitwerk uses Ruby's built-in `autoload`, so this issue is originally caused by `autoload`.

I'll create a pull request to fix this issue soon. I hope you can check it out.

* * *

Note: You can reproduce the `autoload` and `defined?` behavior as follows:

1. Put `sample.rb`:
   ```rb
   class Sample
   end
   ```
1. Run `ruby -e 'p defined?(Sample)'` in your shell:
   * You will see `nil` because `Sample` isn't loaded
1. Run `ruby -e 'autoload :Sample, "./sample"; p defined?(Sample)'` in your shell:
   * You will see `"constant"` even though `Sample` isn't loaded because `Sample` is an autoload constant

**Comment by renodor** [comment]
We are experiencing the same issue.
- Gem version: `3.0.0`
- Ruby version: `3.1.2`
- Rails version: `6.1.7`

Rspec error when running specs:

```
Failure/Error: require "rspec/rails"

GoogleAuthenticatorRails::ActionController::RailsAdapter::LoadedTooLateError:
  GoogleAuthenticatorRails is trying to prepend a before_filter in ActionController::Base.  Because you've already defined ApplicationController, your controllers will not get this before_filter.  Please load GoogleAuthenticatorRails before defining ApplicationController.
```

**Comment by jaredonline** [comment]
Heya @kg8m and @renodor just pushed 3.1.0 of the gem with your changes; should be fixed!

**Comment by kg8m** [comment]
Thank you so much!
