### ISSUE TITLE
[Error] prepend a before_filter in ActionController::Base 

### ISSUE THREAD

**Issue by avvari-da** [jaredonline/google-authenticator#91]
Am getting the following error.
```
GoogleAuthenticatorRails is trying to prepend a before_filter in ActionController::Base. Because you've already defined ApplicationController, your controllers will not get this before_filter. Please load GoogleAuthenticatorRails before defining ApplicationController.
```

I have `ApiController` & `ApplicationController` both defined as follows:
`class ApiController < ActionController::API`
`class ApplicationController < ActionController::Base`

Am on:
`ruby '2.7.7'`
`rails '6.1.7.3'`

Please help me solve this!
Thanks in advance!

**Comment by jaredonline** [comment]
@avvari-da I think this will be fixed by the latest version, can you check?
